{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileSupportError"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"codeListing","syntax":null,"code":["case notReadable"]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Klemens Muthmann"}]}],"type":"aside","name":"Author"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0.0"}]}],"type":"aside","name":"Version"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/datacapturing\/filesupporterror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/DataCapturing\/s5ErrorP","doc:\/\/DataCapturing\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Errors created by the Cyface SDK associated with accessing the file system."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileSupportError"}],"title":"FileSupportError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:13DataCapturing16FileSupportErrorO","modules":[{"name":"DataCapturing"}],"navigatorTitle":[{"kind":"identifier","text":"FileSupportError"}]},"hierarchy":{"paths":[["doc:\/\/DataCapturing\/documentation\/DataCapturing"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError\/notReadable(cause:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError\/Error-Implementations"],"generated":true}],"references":{"doc://DataCapturing/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/DataCapturing\/s8SendableP"},"doc://DataCapturing/documentation/DataCapturing/FileSupportError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/datacapturing\/filesupporterror\/error-implementations"},"doc://DataCapturing/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/DataCapturing\/s5ErrorP"},"doc://DataCapturing/documentation/DataCapturing/FileSupportError":{"role":"symbol","title":"FileSupportError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileSupportError"}],"abstract":[{"type":"text","text":"Errors created by the Cyface SDK associated with accessing the file system."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileSupportError"}],"url":"\/documentation\/datacapturing\/filesupporterror"},"doc://DataCapturing/documentation/DataCapturing":{"role":"collection","title":"DataCapturing","abstract":[],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing","kind":"symbol","type":"topic","url":"\/documentation\/datacapturing"},"doc://DataCapturing/documentation/DataCapturing/FileSupportError/notReadable(cause:)":{"role":"symbol","title":"FileSupportError.notReadable(cause:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReadable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This error is thrown if the file system was not readable."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/FileSupportError\/notReadable(cause:)","kind":"symbol","type":"topic","url":"\/documentation\/datacapturing\/filesupporterror\/notreadable(cause:)"}}}