{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This tells the caller, whether an asynchronous call has been successful or not and if not it provides further information about the "},{"type":"codeVoice","code":"Error"},{"type":"text","text":". This is required, since an asynchronous call can not throw an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" to the calling thread."}]},{"type":"codeListing","syntax":null,"code":["case success","case error(Error)"]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Klemens Muthmann"}]}],"type":"aside","name":"Author"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0.2"}]}],"type":"aside","name":"Version"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.2.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use Swift 5 Result or Swift 5.5 async\/await"}]}],"variants":[{"paths":["\/documentation\/datacapturing\/status"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/Status","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The status returned by asynchronous callback handlers."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"Status"}],"role":"symbol","title":"Status","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"symbolKind":"enum","externalID":"s:13DataCapturing6StatusO","modules":[{"name":"DataCapturing"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/DataCapturing\/documentation\/DataCapturing"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DataCapturing\/documentation\/DataCapturing\/Status\/error(_:)","doc:\/\/DataCapturing\/documentation\/DataCapturing\/Status\/success"]}],"references":{"doc://DataCapturing/documentation/DataCapturing":{"role":"collection","title":"DataCapturing","abstract":[],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing","kind":"symbol","type":"topic","url":"\/documentation\/datacapturing"},"doc://DataCapturing/documentation/DataCapturing/Status/success":{"role":"symbol","title":"Status.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[{"type":"text","text":"The status returned if an asynchronous callback has finished successfully."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/Status\/success","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/datacapturing\/status\/success"},"doc://DataCapturing/documentation/DataCapturing/Status":{"deprecated":true,"role":"symbol","title":"Status","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"abstract":[{"type":"text","text":"The status returned by asynchronous callback handlers."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/Status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Status"}],"url":"\/documentation\/datacapturing\/status"},"doc://DataCapturing/documentation/DataCapturing/Status/error(_:)":{"role":"symbol","title":"Status.error(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The status returned if an asynchronous callback has finished with an error. Details about the error are available via the "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" parameter."}],"identifier":"doc:\/\/DataCapturing\/documentation\/DataCapturing\/Status\/error(_:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/datacapturing\/status\/error(_:)"}}}